# Generated by Django 5.0.2 on 2024-02-24 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('megamarket', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PromoLink',
            new_name='Link',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='link',
            new_name='link_code',
        ),
    ]
